export const demoData = [
    {
        "sto_id": 1,
        "sto_apply_id": 1,
        "sto_name": "泱茶YUMTEA",
        "sto_class": "咖啡輕食",
        "sto_img": "http://localhost:3001/file/images/store/1657970277783--logo_01_泱茶.jpeg",
        "sto_tel": "0800-520-066",
        "sto_location": "101",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 1,
        "sto_pay4": 0,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 0,
        "sto_thu": "10:00",
        "sto_fri": "20:00",
        "sto_sat": "10:00",
        "sto_sun": "20:00",
        "sto_fb": "http://www.facebook.com/yumteaofficial",
        "sto_ins": "http://www.instagram.com/yumteaofficial",
        "sto_line": "",
        "sto_info": " 就是這個味道 泱茶讓茶有更多可能\n 雲芝莓果派對\n 酸甜好滋味，採用百分百鮮果\n 好喝的同時，也要喝的安心喔\n 甜心珍珠+紅玉鮮奶茶\n 台灣的在地好茶，順口又回甘\n 天然紅趜的珍珠，Q彈無負擔\n 香檸蜜烏龍\n 手工熬煮的黑糖，天然甘甜味\n 檸檬蜜搭配烏龍，酸甜好解渴\n 泱泱西瓜\n 粉色的夢幻感，拍照打卡最特別\n 細膩冰沙口感，天然的消暑聖品\n 感謝照片拍攝提供 @wty_food \n 品牌諮詢專線0800-520-066\n 台中草悟店-台中市英才路534號\n 竹北遠百店-竹北大遠百B2 誠品\n 日本池袋店-池袋東口PARCO本館B2\n 日本大阪店-大阪市日本橋一丁目17-22",
        "sto_sta": 1,
        "sto_main": 0,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970578813--first_01_泱茶.jpeg",
        "sto_floor": "1f"
    },
    {
        "sto_id": 2,
        "sto_apply_id": 2,
        "sto_name": "米弎豆お茶処MISATO",
        "sto_class": "咖啡輕食",
        "sto_img": "http://localhost:3001/file/images/store/1657970327778--logo_02_米弎豆.jpeg",
        "sto_tel": "0968-865-380",
        "sto_location": "102",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 1,
        "sto_pay4": 0,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 0,
        "sto_thu": "11:00",
        "sto_fri": "18:00",
        "sto_sat": "11:00",
        "sto_sun": "18:00",
        "sto_fb": "http://www.facebook.com/米弎豆Misato-100470168293789",
        "sto_ins": "http://www.instagram.com/misato.machitea_park2",
        "sto_line": null,
        "sto_info": "【MISATO X 大福製作概念】\nPARK2草悟店限定\n新品節慶預報 - \n芋・塩つけ卵大福 / 芋頭塩奶皇大福\nMISATO in PARK2\n-\n蒐集公園的生活知覺\n在悠憩時光\n拾起每個柔軟包覆的感受\n大福製作概念便是 \n-\n用最柔軟的白皮外衣\n緩緩展開，輕輕包覆\n- 日常每種關於甜的感受\n   米弎豆・芋・塩つけ卵大福 禮盒\n   端午限定優惠活動\n- 禮盒優惠價格200元（原價220)\n《線上宅配》預訂請先填寫以下表單\nhttps://www.surveycake.com/s/RxoPy\n《現場購買》請至草悟PARK2現場直接購買或電話預購\n台中市西區英才路534號1F\n★若有相關問題，請於營業時間內（11:30-19:30）撥打電話詢問\n★連絡電話：0968-865-380",
        "sto_sta": 1,
        "sto_main": 0,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970589020--first_02_米弎豆.jpeg",
        "sto_floor": "1f"
    },
    {
        "sto_id": 3,
        "sto_apply_id": 3,
        "sto_name": "12AM Lifestyle",
        "sto_class": "購物",
        "sto_img": "http://localhost:3001/file/images/store/1657970337575--logo_03_12AM.png",
        "sto_tel": "04-23011659",
        "sto_location": "103",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 0,
        "sto_pay4": 0,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 1,
        "sto_thu": "12:00",
        "sto_fri": "20:00",
        "sto_sat": "12:00",
        "sto_sun": "20:00",
        "sto_fb": "http://www.facebook.com/12amlifestyle-101848569190755",
        "sto_ins": "http://www.instagram.com/12am.lifestyle",
        "sto_line": null,
        "sto_info": "12am，00:00，midnight，在夜色裡交換日子的一瞬，同時坐擁一天的結束與開端。對我們來說，這個屬於過渡的片刻是全然自由的，每個人都能以自己的方式賦予它定義，也因此 12am 使我們對它深深著迷。在12am，你能找到完整日常儀式的那塊拼圖，讓儀式觸發轉化，點亮你對這一刻最個人化的定義。\n \n 12am 成立於 2022 年，午夜之光股份有限公司在台中 Park2 草悟廣場創立概念店，我們為你獻上翻新感官的提案，喚醒身體裡的每一個反叛細胞。我們著迷於 12am 這個時分，它代表著一日紛亂的結尾，也象徵著即將迎接新日光的起點，該如何定義，隨心而搖曳，每個人都能以自己的方式賦予它定義。在這私隱的時刻，12am 不拋擲任何評述，讓每份思緒都能恣意生長，並以溫柔的方式陪伴你們度過陰晴起伏。\n \n 我們堅信只要更有意識的體會每個平凡情景，便能增加生活的厚度。團隊致力於在世界各地蒐羅承載濃郁獨特風格的品牌，不斷探索能巧妙融入日常生活的單品。 12am 渴望為在生活中奔波的你，挑揀出能提升身心質感的物品，讓你的生活成為精選後的模樣。你可以放心地從 12am 官網訂購任何商品，我們保證所有的產品都是正品，皆是直接與品牌或官方經銷商處採購。",
        "sto_sta": 1,
        "sto_main": 1,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970597137--first_03_12AM.jpeg",
        "sto_floor": "1f"
    },
    {
        "sto_id": 4,
        "sto_apply_id": null,
        "sto_name": "每果發光",
        "sto_class": "咖啡輕食",
        "sto_img": "http://localhost:3001/file/images/store/1657970346141--logo_04_每果發光.png",
        "sto_tel": "04-23012026",
        "sto_location": "104",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 1,
        "sto_pay4": 1,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 0,
        "sto_thu": "11:00",
        "sto_fri": "20:00",
        "sto_sat": "11:00",
        "sto_sun": "20:00",
        "sto_fb": "http://www.facebook.com/Mayglow每果發光-104283345565413/",
        "sto_ins": "http://www.instagram.com/mayglow.superfood",
        "sto_line": null,
        "sto_info": "You May Glow\n \n 專注身體能量｜回歸純粹本質\n \n 以天然純淨飲食哲學 喚醒身心靈的平衡與愉悅\n \n &middot;\n \n 每果發光陪伴你每個發光時刻 超級食物4大益處?\n \n 1. 抗氧化 是皮膚最好的朋友\n \n 2. 高維他命含量\n \n 3. 排毒療癒好消化\n \n 4. 天然無添加\n \n 甜味皆來自蔬果本身 邀請你一同享用\n \n 輕盈美味的超級食物",
        "sto_sta": 1,
        "sto_main": 1,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970603956--first_04_每果發光.jpeg",
        "sto_floor": "1f"
    },
    {
        "sto_id": 17,
        "sto_apply_id": null,
        "sto_name": "Para coffee",
        "sto_class": "咖啡輕食",
        "sto_img": "http://localhost:3001/file/images/store/1658365817823--logo_Para coffee.jpeg",
        "sto_tel": "04-23010103",
        "sto_location": "105",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 1,
        "sto_pay4": 1,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 0,
        "sto_thu": "11:00",
        "sto_fri": "20:00",
        "sto_sat": "11:00",
        "sto_sun": "20:00",
        "sto_fb": "http://www.facebook.com/para.coffee",
        "sto_ins": "http://www.instagram.com/para_coffee",
        "sto_line": "",
        "sto_info": "簡單點一杯 不簡單的咖啡\r\n _\r\n用喜歡風味探索0-6\r\n簡單選擇，滿足你不簡單的味蕾\r\n今天，PARA幾號？\r\n 1 淺焙 甜桃 柑橘 白花 檸檬紅茶\r\n 2 淺中焙 熟桃 香蕉 菊花 高山茶\r\n 3 中焙 李子 楓糖 茶梅 奶油\r\n 4 中深焙 巧克力 煙燻 焦糖 松木\r\n 5 中焙 百香果 熟橘 甜橙\r\n 6 中焙 烏梅 黑醋栗 果茶\r\n 0 歐蕾 冷萃與燕麥奶的交織平衡\r\n #paracoffee",
        "sto_sta": 1,
        "sto_main": 0,
        "sto_first_img": "http://localhost:3001/file/images/store/1658365817824--Para coffee.jpeg",
        "sto_floor": "1f"
    },
    {
        "sto_id": 6,
        "sto_apply_id": null,
        "sto_name": "正面奶酥",
        "sto_class": "購物",
        "sto_img": "http://localhost:3001/file/images/store/1657970362453--logo_06_正面奶酥.jpeg",
        "sto_tel": "04-23010103",
        "sto_location": "106",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 0,
        "sto_pay4": 0,
        "sto_pay5": 0,
        "sto_pay6": 1,
        "sto_pay7": 0,
        "sto_thu": "12:00",
        "sto_fri": "20:00",
        "sto_sat": "12:00",
        "sto_sun": "20:00",
        "sto_fb": "http://www.facebook.com/positiveyummy",
        "sto_ins": "http://www.instagram.com/positive_yummy",
        "sto_line": null,
        "sto_info": "闆娘9歲開始吃，現在決定分大家一起吃\n \n 這世界太複雜、太負面 我們都需要正面奶酥。\n \n ●奶酥醬官網訂購\n \n 全手工製作！急單勿下單！\n \n 絕對需要2個月以上(你快忘記時就來了)\n \n ●現烤奶酥這裡吃\n \n 台中｜西區英才路537號(PARK2草悟廣場)\n \n 台北｜信義區松壽路18號1F(信義威秀)",
        "sto_sta": 1,
        "sto_main": 1,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970619551--first_06_正面奶酥.jpeg",
        "sto_floor": "1f"
    },
    {
        "sto_id": 7,
        "sto_apply_id": null,
        "sto_name": "COFFEE AND JOHN",
        "sto_class": "咖啡輕食",
        "sto_img": "http://localhost:3001/file/images/store/1657970372446--logo_07_COFFEE AND JOHN.jpeg",
        "sto_tel": "04-23010103",
        "sto_location": "107",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 1,
        "sto_pay4": 1,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 1,
        "sto_thu": "11:00",
        "sto_fri": "20:00",
        "sto_sat": "11:00",
        "sto_sun": "20:00",
        "sto_fb": "http://www.facebook.com/coffeeandjohn",
        "sto_ins": "http://www.instagram.com/coffeeandjohn.tw",
        "sto_line": null,
        "sto_info": "YO, I'M JOHN FROM NEW YORK.\nCOFFEE AND JOHN 新款短Tee \"Good Day\" 上市啦！\n門市和線上商店 同步開賣！\n短Tee背面有插畫家柴田昌達先生為開幕特別繪製的插畫：JOHN坐著滑板於城市中休憩的樣貌，同時不忘來一杯咖啡，展現EVERYDAY IS A GOOD DAY的生活理念。胸前以JOHN的滑板搭配COFFEE AND JOHN字樣刺繡，並於底部描繪出滑行速度感的趣味細節。本款有白色、灰色可供選擇。\n寬鬆落肩的板型與前短後長的層次剪裁，搭配厚實的高品質棉質面料，為穿著時帶來Oversized輪廓與舒適穿著體驗。\n-\nCOFFEE AND JOHN \n\"EVERYDAY IS A GOOD DAY.\"\n營業時間：每日11點至20點\n營業地點：PARK2 草悟廣場 1F  \n-\n關於 COFFEE AND JOHN",
        "sto_sta": 1,
        "sto_main": 1,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970628607--first_07_COFFEE AND JOHN.jpeg",
        "sto_floor": "1f"
    },
    {
        "sto_id": 8,
        "sto_apply_id": null,
        "sto_name": "酉5PM TWCAUDEX",
        "sto_class": "藝術設計",
        "sto_img": "http://localhost:3001/file/images/store/1657970381706--logo_08_酉.jpeg",
        "sto_tel": "04-23010103",
        "sto_location": "108",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 1,
        "sto_pay4": 0,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 0,
        "sto_thu": "11:00",
        "sto_fri": "19:00",
        "sto_sat": "11:00",
        "sto_sun": "19:00",
        "sto_fb": "http://www.facebook.com/5pm.twcaudex",
        "sto_ins": "http://www.instagram.com/5pm.twcaudex",
        "sto_line": "https://line.me/R/ti/p/%40flv6197c",
        "sto_info": "「酉」台灣第一間專為塊根植物所建立的專門店，從店內到店外及建築物均為老闆一手設計，簡約的幾何清水模建築及透亮的玻璃溫室，並搭配戶外的沙漠造景，營造出原始生態的生長樣貌。\n \n 酉 &mdash;&mdash; 代表傍晚5點至7點。\n \n 日落的夕陽，溫暖的光綫\n \n 照射在植物上是最美的時刻\n \n 酉時，也是澆水的最佳時間\n \n 漫射的光，輝映在水珠上，更顯植物獨特的美。\n \n 專營乾旱植栽造景規劃及特殊品種植物進口\n \n 藝術家及創作者聯名合作器皿、花器、藝術擺件\n \n 目前主設計公司為 &mdash; 泳豐澤有限公司\n \n 公司旗下品牌\n \n 「酉Succulent &amp; Artwork」\n \n ｜酉5PM LANDSCAPE｜\n \n ｜酉5PM TWCAUDEX｜\n \n ｜酉5PM DESSERT｜\n \n 公司積極投入及鑽研於建築環境綠化及特殊造景\n \n 目標為結合建築本身及室內外空間使用\n \n 致力成為新尺度景觀規劃的新興企業\n \n 未來將投入於集合住宅及都會型景觀空間規劃， 創造更多與自然空間接觸機會，使現社會與自然並行， 支持國內外新一代創作者，並提供更友善之交流平台。",
        "sto_sta": 1,
        "sto_main": 0,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970636593--first_08_酉.jpeg",
        "sto_floor": "1f"
    },
    {
        "sto_id": 9,
        "sto_apply_id": null,
        "sto_name": "MOLINO",
        "sto_class": "餐廳",
        "sto_img": "http://localhost:3001/file/images/store/1657970393162--logo_09_MOLINO.jpeg",
        "sto_tel": "04-23020269",
        "sto_location": "B101",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 0,
        "sto_pay4": 0,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 0,
        "sto_thu": "11:00",
        "sto_fri": "21:30",
        "sto_sat": "11:00",
        "sto_sun": "21:30",
        "sto_fb": "http://www.facebook.com/molino.taiwan",
        "sto_ins": "http://www.instagram.com/molino.taiwan",
        "sto_line": "https://page.line.me/836oteyf?openQrModal=true",
        "sto_info": "全台第一間以石臼現磨鮮麥，提供手工義大利麵的義式餐廳，義大利文的MOLINO，指的是「石臼研磨」。MOLINO以石臼磨麥製麵傳統，研發出最美味的手工義大利麵。\n\n麥子品質是關鍵！麥子的品種、硬度及蛋白質含量，左右了麵的口感、吸水度及最重要的風味，以獨家比例調配出最佳風味的手工義大利麵，為的就是留在你口中那淡淡的麥香\n\n顛覆你的刻板印象！義大利麵不只有青、白、紅醬，還能以蔬菜、肉、起司等食材製作。用料變化多端的義大利麵醬汁，根據各種創意麵型、口感，量身打造專屬的醬汁，一種麵型搭配一種醬汁，絕不共醬！",
        "sto_sta": 1,
        "sto_main": 0,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970645775--first_09_MOLINO.jpeg",
        "sto_floor": "b1"
    },
    {
        "sto_id": 10,
        "sto_apply_id": null,
        "sto_name": "新村站著吃烤肉",
        "sto_class": "餐廳",
        "sto_img": "http://localhost:3001/file/images/store/1657970402091--logo_10_新村站著吃烤肉.jpeg",
        "sto_tel": "04-23011659",
        "sto_location": "B102",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 1,
        "sto_pay4": 1,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 1,
        "sto_thu": "12:00",
        "sto_fri": "24:00",
        "sto_sat": "12:00",
        "sto_sun": "24:00",
        "sto_fb": "http://www.facebook.com/standupplzbbq",
        "sto_ins": "http://www.instagram.com/standupplzbbq",
        "sto_line": null,
        "sto_info": "源於1953年開幕至今的首爾名店，被列為「首爾未來遺產」之一。店內特色為繞著石油桶站著吃烤肉，保留了自韓戰以來的獨特用餐方式，同時也打破了傳統燒烤店的座位限制，讓店內每個人都能夠自由移動暢談酣飲，呈現了特別的活絡氣氛。台灣團隊經過將近1年的接洽溝通，打破首爾本店「絕無分店」的營運原則，終於在台北市信義區開設全球第一間分店，更於2021年12月於台中開設2號店，未來也積極規劃在全台擴點，讓大家都能體驗到輕鬆愉快並獨具特色的韓式烤肉。\n 台灣店招牌的橫隔膜選用與韓國本店相同的澳洲牧場進口，以求原汁原味體驗。同時為提升享用烤肉的滿足感，台灣一號店有別於韓國老店菜單上只提供單一肉品，特別增加了其他肉品（包含豬、牛）的選項。\n 店內除了延續從韓戰時期以來，單純供應肉品和酒水的點餐方式。再另外以韓國便利商店貨架的形式，販售各式小菜與白飯供大家與烤肉一同享用，結合了韓式便利店與韓式烤肉兩種形式，提供有趣又道地的用餐體驗。\n 身為韓國指標性烤肉名店的台灣代表，新村站著吃烤肉堅持保留韓國本店及當地慣有的用餐習慣，但同時也強調「以酒會友」，融合台韓兩地的飲酒烤肉文化，在店內以讓大家「喝得開心，吃得滿足」為目標，協助每一位客人能真正體驗到「沒有距離」的用餐氣氛，打造專屬於台灣人的韓式酒場。",
        "sto_sta": 1,
        "sto_main": 0,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970653541--first_10_新村站著吃烤肉.jpeg",
        "sto_floor": "b1"
    },
    {
        "sto_id": 11,
        "sto_apply_id": null,
        "sto_name": "ROCKLAND PLUS",
        "sto_class": "購物",
        "sto_img": "http://localhost:3001/file/images/store/1657970415785--logo_11_ROCKLAND PLUS.png",
        "sto_tel": "04-23011881",
        "sto_location": "B103",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 1,
        "sto_pay4": 1,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 0,
        "sto_thu": "12:00",
        "sto_fri": "21:00",
        "sto_sat": "12:00",
        "sto_sun": "21:00",
        "sto_fb": "http://www.facebook.com/plusplustaiwan",
        "sto_ins": "http://www.instagram.com/p.l.u.s.__",
        "sto_line": null,
        "sto_info": "PLEASANT . LIBERAL . UNLIMITED . SYNERGY .\n \n 咖啡 Coffee / 選品 Select / 雜誌 Magazine / 展演空間 Exhibition\n \n 店內空間設計就像是編輯一本3D雜誌，推開店門， 彷彿打開無形的那扇門，城市 / 山林，不再被清晰定義。 讓您發掘，家門以外的風景與事物，其實都存在不經意的日常之中。 商品陳設、餐飲品項設計，皆優先考量使用者的體驗感受，讓客人在這裡能打開五感，去感覺商品最實際的回饋。每個選品都與您分享著P.L.U.S.的生活日常。 不定期邀請各領域專業人士與創作者舉行講座、發表會與手作體驗等，讓多種創意活動，都能在ROCKLAND P.L.U.S.裡發生。",
        "sto_sta": 1,
        "sto_main": 0,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970665868--first_11_ROCKLAND PLUS.jpeg",
        "sto_floor": "b1"
    },
    {
        "sto_id": 12,
        "sto_apply_id": null,
        "sto_name": "TOASTERiA CAFÉ",
        "sto_class": "餐廳",
        "sto_img": "http://localhost:3001/file/images/store/1657970424383--logo_12_TOASTERiA.jpeg",
        "sto_tel": "04-23020093",
        "sto_location": "B104",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 0,
        "sto_pay4": 0,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 0,
        "sto_thu": "9:00",
        "sto_fri": "2:00",
        "sto_sat": "9:00",
        "sto_sun": "2:00",
        "sto_fb": "http://www.facebook.com/TOASTERiACAFEPARK2",
        "sto_ins": "http://www.instagram.com/toasteriacafe",
        "sto_line": null,
        "sto_info": "Toasteria Cafe不只是一間餐廳或是咖啡廳，吐司利亞帶給您的是一趟通往美麗地中海國度的旅程。\n \n 帶你進入這個放鬆的空間是一系列完美和諧的組合：在經典的空間設計享用療癒的道地地中海料理，體驗優質貼心的服務，精挑細選的 世界音樂，彷彿真的來到了地中海。對於屋內各個角落的 設計細節以及結合新與舊的建材，我們團隊都抱持著堅持的態度，因為這樣的理念才能帶您踏上這趟地中海時光之旅。\n \n 一個經典與現代組合的地中海設計，圍繞著您的是花園 的天然綠色夢境。 Toasteria Cafe是一間以開放的心態讓我們的菜單由不同 文化背景豐富我們地中海風格的廚房。有來自以色列、 摩洛哥、埃及、希臘、西班牙、法國、義大利的味道， 一次達成造訪各個國家的夢想。\n \n Toasteria Cafe是您可以在台北市逃離繁忙市區的浪漫蔽所。在Toasteria Cafe，我們認為再細小的環節都是創造舒適、有趣、盡情享受的 重要因素。",
        "sto_sta": 1,
        "sto_main": 1,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970672931--first_12_TOASTERiA.jpeg",
        "sto_floor": "b1"
    },
    {
        "sto_id": 13,
        "sto_apply_id": null,
        "sto_name": "SUNMAI BAR",
        "sto_class": "餐廳",
        "sto_img": "http://localhost:3001/file/images/store/1657970432264--logo_13_SUNMAI BAR.jpeg",
        "sto_tel": "04-23051818",
        "sto_location": "B105",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 1,
        "sto_pay4": 0,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 0,
        "sto_thu": "17:00",
        "sto_fri": "1:00",
        "sto_sat": "17:00",
        "sto_sun": "1:00",
        "sto_fb": "http://www.facebook.com/sunmaibar",
        "sto_ins": "http://www.instagram.com/sunmaibar",
        "sto_line": null,
        "sto_info": "LE BLE D'OR 即為法語「黃金般的麥芽」 提到金色三麥，您可能會想到現釀啤酒。\n \n 金色三麥除了冠軍現釀啤酒之外，更有多樣的異國特色佳餚及風味特調飲品，豐富的選擇可以滿足所有人的胃。 來到金色三麥，您可以盡情陶醉於這裡的啤酒、美食以及歐式風情。\n \n 金色三麥成立的初衷其實很單純，就是「分享」。\n 創辦人葉榮發先生就是希望以「分享」的心態邀請所有朋友一起共享美味。來到店裡可以自在放鬆不受拘束，金色三麥服務精神秉持著「主人心態」，服務人員就如同家裡的主人般，把每一位客人都當成是自己家裡的貴賓、親友，用無比的熱情招待，讓每一位貴賓都擁有難忘而美好的用餐經驗。",
        "sto_sta": 1,
        "sto_main": 1,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970680078--first_13_SUNMAI.jpeg",
        "sto_floor": "b1"
    },
    {
        "sto_id": 14,
        "sto_apply_id": null,
        "sto_name": "公園裡的星期天",
        "sto_class": "藝術設計",
        "sto_img": "http://localhost:3001/file/images/store/1657970442701--logo_14_公園裡的星期天.jpeg",
        "sto_tel": "04-23050929",
        "sto_location": "B106",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 1,
        "sto_pay4": 1,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 0,
        "sto_thu": "9:00",
        "sto_fri": "20:00",
        "sto_sat": "9:00",
        "sto_sun": "20:00",
        "sto_fb": "http://www.facebook.com/sundayinthepark.tw",
        "sto_ins": "http://www.instagram.com/sundayinthepark.ig",
        "sto_line": null,
        "sto_info": "其實說這家店啟發於喬治‧秀拉的『大碗島的星期天下午』，並不完全正確。認真來說，史蒂芬 桑坦的東尼獎音樂劇『Sunday in the Park with George』佔比可能更多一些。我們當然喜愛這幅畫，不管是它的藝術性或者是作者創作背後的那些偏執，但是史蒂芬&middot;桑坦真正的賦予了它生命與更多的寓意，對我們的影響無以名狀。\n \n 在躊躇想著要創立這家店的時候，Sunday in the Park這名字一出現，所有的疑慮就完全消失了，彷彿是一種命定的必然，那一刻起，這個名字與這間店的一切，還有我們自己本身，都產生了一種連結，宛如共生。 我們很少談論這間店的由來，畢竟創作者時時談論著自己的初衷總是令人覺得矯情，但或許今天，有一點哀傷是被允許的。 Rest easy, and rest assured that your work will live on forever.",
        "sto_sta": 1,
        "sto_main": 0,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970686756--first_14_公園裡的.jpeg",
        "sto_floor": "b1"
    },
    {
        "sto_id": 15,
        "sto_apply_id": null,
        "sto_name": "ROCKLAND",
        "sto_class": "藝術設計",
        "sto_img": "http://localhost:3001/file/images/store/1657970452282--logo_15_ROCKLAND.png",
        "sto_tel": "04-23011611",
        "sto_location": "B107",
        "sto_pay1": 1,
        "sto_pay2": 1,
        "sto_pay3": 0,
        "sto_pay4": 0,
        "sto_pay5": 1,
        "sto_pay6": 1,
        "sto_pay7": 0,
        "sto_thu": "12:00",
        "sto_fri": "21:00",
        "sto_sat": "12:00",
        "sto_sun": "21:00",
        "sto_fb": "http://www.facebook.com/RocklandTaiwan",
        "sto_ins": "http://www.instagram.com/rockland_taiwan",
        "sto_line": null,
        "sto_info": "成立於1997年，以Travel 、Outdoor、Nature 為出發點，堅守著「讓大家能無憂的享受戶外生活；幫忙嚴選把關」的理念，成為多個嚴選戶外品牌的台灣獨家代理。代理品牌以環境為出發點，在進行戶外活動的同時，也倡導人與自然和平共存的環境永續。",
        "sto_sta": 1,
        "sto_main": 0,
        "sto_first_img": "http://localhost:3001/file/images/store/1657970695767--first_15_ROCKLAND.jpeg",
        "sto_floor": "b1"
    }
]